version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

volumes:
  db_data:
    driver:local
    driver_opts:
      type: none
      device: /home/aquincho/data/mysql
      o: bind


networks:
  network:
    driver: bridge