version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    #  - mariadb
    ports:
      - "443:443"
    #  - 80:80
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: worpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WORDPRESS}
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB}
      o: bind


networks:
  inception_network:
    driver: bridge